# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("640x480")
window.configure(bg="#62568c")
window.title("FlashBackup")

canvas = tk.Canvas(
    window,
    bg = "#62568c",
    width = 640,
    height = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

image_1 = tk.PhotoImage(file=load_asset("1.png"))

canvas.create_image(337, 298, image=image_1)

button_2_image = tk.PhotoImage(file=load_asset("2.png"))

button_2 = tk.Button(
    image=button_2_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=372, y=222, width=210, height=30)

button_3_image = tk.PhotoImage(file=load_asset("3.png"))

button_3 = tk.Button(
    image=button_3_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 has been pressed!")
)

button_3.place(x=423, y=294, width=115, height=35)

button_1_image = tk.PhotoImage(file=load_asset("4.png"))

button_1 = tk.Button(
    image=button_1_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=372, y=150, width=210, height=30)

button_4_image = tk.PhotoImage(file=load_asset("5.png"))

button_4 = tk.Button(
    image=button_4_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 has been pressed!")
)

button_4.place(x=582, y=420, width=50, height=50)

window.resizable(False, False)
window.mainloop()
