# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("895x552")
window.configure(bg="#aa6f6f")
window.title("Untitled")

canvas = tk.Canvas(
    window,
    bg = "#aa6f6f",
    width = 895,
    height = 552,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    22,
    46,
    anchor="nw",
    text="BUTTON:",
    fill="#ffffff",
    font=("Inter", 12 * -1)
)

class TkForge_Entry(tk.Entry):
    def __init__(self, master=None, placeholder="Enter text", placeholder_fg='grey', **kwargs):
        super().__init__(master, **kwargs)
        
        self.p, self.p_fg, self.fg = placeholder, placeholder_fg, self.cget("fg")
        self.putp()
        self.bind("<FocusIn>", self.toggle)
        self.bind("<FocusOut>", self.toggle)

    def putp(self):
        self.delete(0, tk.END)
        self.insert(0, self.p)
        self.config(fg=self.p_fg)
        self.p_a = True

    def toggle(self, event):
        if self.p_a:
            self.delete(0, tk.END)
            self.config(fg=self.fg)
            self.p_a = False
        elif not self.get(): self.putp()

    def get(self): return '' if self.p_a else super().get()

    def is_placeholder(self, b):
        self.p_a = b
        self.config(fg=self.p_fg if b == True else self.fg)

    def get_placeholder(self): return self.p

button_1_image = tk.PhotoImage(file=load_asset("1.png"))

button_1 = tk.Button(
    image=button_1_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=166, y=60, width=56, height=49)

button_2_image = tk.PhotoImage(file=load_asset("2.png"))

button_2 = tk.Button(
    image=button_2_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=22, y=71, width=123, height=27)

image_1 = tk.PhotoImage(file=load_asset("3.png"))

canvas.create_image(83, 37, image=image_1)

canvas.create_text(
    12,
    170,
    anchor="nw",
    text="textbox:",
    fill="#ffffff",
    font=("Inter", 12 * -1)
)

textbox_1 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0,
    placeholder="daun   "
    
)

textbox_1.place(x=12, y=189, width=137, height=36)

canvas.create_text(
    275,
    0,
    anchor="nw",
    text="Image:",
    fill="#ffffff",
    font=("Inter", 12 * -1)
)

image_2 = tk.PhotoImage(file=load_asset("4.png"))

canvas.create_image(408, 89, image=image_2)

window.resizable(False, False)
window.mainloop()
